source("gene_count_module.R")
Enriched_markers_module_UI<-function(id)
{
  ns<-NS(id)
  tagList(
    fluidRow(column(10,bsAlert("Anchor3"))),
    br(),
    br(),
    fluidRow(column(10,DT::dataTableOutput(ns("TF_genes")))),
    br(),
    hr(),
    radioButtons(ns("lfc_TF"), "Show log2 foldchange?:", choices = c("Yes", "No"),selected = "No"),
    br(),
    fluidRow(
      column(1,
             selectInput(ns("datachoice5")  ,label = h5("Select Data Type"), 
                         choices = list("Excel" = 1, "CSV" = 2),
                         selected = 1)),
      column(1, 
             br(),
             br(),
             downloadButton(ns('download_DE_TF_Table'), 'Download List of Transcription Factors'))),
    DT::dataTableOutput(ns("filtered_TF")),
    br(),
    br(),
    gene_count_module_UI(ns("module3"))

  )
}




#Transcription factor
#Compute the Transcription factor based on a list for a list of DE genes
#Construct  a matrix where row->comparison A vs B, C vs D .etc
# columns (up regulated genes, down regulated genes, all DE genes)
#Loop through a similar matrix generated by reactive DE_genes)
#Filter TF for each element in the matrix generated by reactive DE_genes

Enriched_markers_module<-function(input,output,session,call,TF_list,organism,
                                  DE_genes,combination,CoCena,
                                  conchoice,normal,dds.fc,batch_choice,
                                  batch_corrected,anova_table,dds)
{
  combo<-combination()
  num<-length(combo())
  DE_TF<-reactive({
    result_DE<-DE_genes()
    
    if(!is.null(CoCena()))
    {
        cluster_info<-as.data.frame(CoCena()$cluster_calc()[CoCena()$cluster_calc()$cluster_included=="yes",])
        combo<-combination()
        num<-length(combo())
        Enriched_transcription_factors(TF_list(),result_DE,num,organism(),cluster_info,
                                       anova_table(),conchoice(),dds())
      
    }
    else
    {
      combo<-combination()
      num<-length(combo())
      Enriched_transcription_factors(TF_list(),result_DE,num,organism(),NULL,NULL,NULL,NULL)
    }
   
    
  })
  
  #display summary of TF
  output$TF_genes <- DT::renderDataTable({
    if((call == "TF" & organism() %in% c("Homo sapiens", "Mus musculus")) | (call == "marker"))
    {
      closeAlert(session,"Organism2")
    result<-DE_TF()
    rows<-num
    
    res<-NULL
    
    if(!is.null(CoCena()))
    {
        cluster_info<-as.data.frame(CoCena()$cluster_calc()[CoCena()$cluster_calc()$cluster_included=="yes",])
        
        entry<-c(as.vector(combo()), as.vector(cluster_info$color))
        rows<-length(entry)
        res<-data.frame(matrix(NA, nrow = rows, ncol = 3))
        colnames(res)<-c('Up regulated','Down regulated','Both')

        rownames(res)<-lapply(1:rows, function(i) {
          unlist(entry[i])
          
        })
        for(i in 1:length(combo()))
        {
          res[i,1]<-nrow(as.data.frame(result[[i]][1]))
          res[i,2]<-nrow(as.data.frame(result[[i]][2]))
          res[i,3]<-nrow(as.data.frame(result[[i]][3]))
        }
        for(i in (1+length(combo())):(nrow(cluster_info)+length(combo())))
        {
          print(i)
          res[i,1:2]<-0
          res[i,3]<-nrow(as.data.frame(result[[i]][3]))
        }
      
    }
    else{
      res<-data.frame(matrix(NA, nrow = length(combo()), ncol = 3))
      rownames(res)<-lapply(1:length(combo()), function(i) {
        combo()[[i]]
        
      })
      colnames(res)<-c('Up regulated','Down regulated','Both')
      for(i in 1:length(combo()))
      {
        res[i,1]<-nrow(as.data.frame(result[[i]][1]))
        res[i,2]<-nrow(as.data.frame(result[[i]][2]))
        res[i,3]<-nrow(as.data.frame(result[[i]][3]))
      }
    }
    DT::datatable(res,class = 'cell-border stripe',
                  selection = list(mode='single',target = 'cell'),
                  extensions = list('Scroller'=NULL,'Buttons'=NULL),
                  options = list(deferRender = TRUE,scrollX = TRUE,scrollY = 150,scroller = TRUE,dom = 'Bfrtip',
                                 buttons = list(list(extend = 'collection',buttons = c('csv', 'excel', 'pdf'),
                                                             text = 'Download table'))),
                  
                  escape = FALSE
    )
    } else {
      createAlert(session, "Anchor3", "Organism2", title = "Error",
                  content = "This module is not available for the chosen organism!")
    } 
  })
  
  observeEvent(input$TF_genes_cell_clicked,{

    selected <- input$TF_genes_cells_selected
    row<-selected[1]
    col<-selected[2]
    if(length(selected)>0){
      #Display list of selected transcription factors 
      output$filtered_TF <- DT::renderDataTable({
        result<-DE_TF()
        if(!is.null(CoCena()))
        {
            if(row>length(combo())){
            
              gene_list<-  as.data.frame(character())
            if(col==3) gene_list<-result[[row]][[col]]

            DT::datatable(gene_list,class = 'cell-border stripe',
                          selection = list(mode='single',target = 'row'),
                          extensions = list('Scroller'=NULL,'Buttons'=NULL),
                          options = list(deferRender = TRUE,scrollX = TRUE,scrollY = 150,scroller = TRUE,dom = 'Bfrtip',
                                         buttons = list()))
            }
            else if(row<=length(combo()))
              {
              df<-as.data.frame(result[[row]][[col]])

              df_final<- df[order(df$padj),]
              colnames(df_final)[1]<-"Overall mean"
              for (i in 8:length(colnames(df_final)))
              {
                colnames(df_final)[i]<-paste(colnames(df_final)[i],"mean")
              }
              a_tab<-df_final[,-4]
              df_TF=NULL
              if(input$lfc_TF =="No")
              {
                names<-colnames(a_tab)
                df_TF=a_tab[,-3]
              }
              else df_TF=a_tab
              DT::datatable(df_TF,class = 'cell-border stripe',
                            selection = list(mode='single',target = 'row'),
                            extensions = list('Scroller'=NULL,'Buttons'=NULL),
                            options = list(deferRender = TRUE,scrollX = TRUE,scrollY = 150,scroller = TRUE,dom = 'Bfrtip',
                                           buttons = list()))
              }
           
          
        }
        else {
          df<-as.data.frame(result[[row]][[col]])

          df_final<- df[order(df$padj),]
          colnames(df_final)[1]<-"Overall mean"
          for (i in 8:length(colnames(df_final)))
          {
            colnames(df_final)[i]<-paste(colnames(df_final)[i],"mean")
          }
          a_tab<-df_final[,-4]
          df_TF=NULL
          if(input$lfc_TF =="No")
          {
            names<-colnames(a_tab)
            df_TF=a_tab[,-3]
          }
          else df_TF=a_tab
          DT::datatable(df_TF,class = 'cell-border stripe',
                        selection = list(mode='single',target = 'row'),
                        extensions = list('Scroller'=NULL,'Buttons'=NULL),
                        options = list(deferRender = TRUE,scrollX = TRUE,scrollY = 150,scroller = TRUE,dom = 'Bfrtip',
                                       buttons = list()))
        }
        
      })
      #plot counts of gene
      #disply boxplot for the marker gene selected in the marker gene table
      observeEvent(input$filtered_TF_rows_selected,{
        #get which gene was clicked
        #get the row  number of the gene clicked
        selected_row <- input$filtered_TF_rows_selected
        print(selected_row)
        #get the normalized data
        full_data<-normal()
        #get the DE table where we clicked the gene
        selected <- input$TF_genes_cells_selected
        row<-selected[1]
        col<-selected[2]

        if(length(selected)>0)
        {
          #get the table where we clicked the TF
          result<-DE_TF()
          df<-NULL
          df_final<-NULL

          if(row<=length(input$combination))
          {
            df<-as.data.frame(result[[row]][[col]])
            df_final<- df[order(df$padj),]
          }
          else if(row>length(input$combination))
          {
            df_final<-result[[row]][[3]]
          }
          #get the gene
          an_gene<-rownames(df_final)[selected_row]

          counts<-as.vector(full_data[which(an_gene %in% rownames(full_data)),])
          cond<-as.vector(colData(dds.fc()[[1]])[,as.numeric(conchoice())])

          library('data.table')
          df<-data.frame(counts,cond)
          colnames(df)<-c('count','condition')
          batch<-batch_choice()
          if(as.numeric(batch)==1) callModule(gene_count_module,"module3",NULL,reactive({dds.fc()[[1]]}),reactive({an_gene}))
          else 
            {
              idx<-which(rownames(batch_corrected()) %in% an_gene)
              callModule(gene_count_module,"module3",batch_corrected()[idx,],reactive({dds.fc()[[1]]}),reactive({an_gene}))
            }
        }
      })
      #download Transcription factors
      output$download_DE_TF_Table <- downloadHandler(
        
        filename = function(){ 
        
          if (as.numeric(input$datachoice5==1))  
          {
          if(row<=length(input$combination))
          {
          condition<-combo()[[row]]
          if(col==1) paste('Up regulated TF for ',condition,'.xlsx')
          else if(col==2) paste('Down regulated TF for ',condition,'.xlsx')
          else paste('All DE TF for ',condition,'.xlsx')
          }
          else{
            cluster_info<-as.data.frame(CoCena()$cluster_calc()[CoCena()$cluster_calc()$cluster_included=="yes",])
            paste('ANOVA table for TF in module ',cluster_info$color[row],'.xlsx')
          }
         
        }
        else {
          
          if(row<=length(input$combination))
          {
            condition<-combo()[[row]]
            if(col==1) paste('Up regulated TF for ',condition,'.csv')
            else if(col==2) paste('Down regulated TF for ',condition,'.csv')
            else paste('All DE TF for ',condition,'.csv')
          }
          else{
            cluster_info<-as.data.frame(CoCena()$cluster_calc()[CoCena()$cluster_calc()$cluster_included=="yes",])
            paste('ANOVA table for TF in module ',cluster_info$color[row],'.csv')
          }
        }},
          
        
        
        content = function(file) {
          if (as.numeric(input$datachoice5==1)){  
          #sort by adjusted p value.
          result<-DE_TF()
          df_final<-as.data.frame(character(0))
          nam<-"Sheet1"
          if(row<=length(input$combination))
          {
          df<-as.data.frame(result[[row]][[col]])
          df_final<- df[order(df$padj),]
          colnames(df_final)[1]<-"Overall mean"
          for (i in 8:length(colnames(df_final)))
          {
            colnames(df_final)[i]<-paste(colnames(df_final)[i],"mean")
          }
          nam<-"Sheet 1"
          condition<-combo()[[row]]
          condition<-str_replace_all(condition,"[^[:alnum:]]",".")
          if(col==1) nam<-paste('Up regulated TF for ',condition)
          else if(col==2) nam<-paste('Down regulated TF for ',condition)
          else nam<-paste('All DE TF for ',condition)
          }
          else{
            df_final<-result[[row]][[4]]
            cluster_info<-as.data.frame(CoCena()$cluster_calc()[CoCena()$cluster_calc()$cluster_included=="yes",])
            nam<-paste('ANOVA table for TF in module ',cluster_info$color[row])
          }
          M <- as.matrix(df_final)
          wb <- createWorkbook()
          addWorksheet(wb, sheetName = "TF table")
          writeData(wb = wb, sheet = 1, x = M, colNames = T, rowNames = T)
          saveWorkbook(wb, file)
        }
          else{
            result<-DE_TF()
            df_final<-as.data.frame(character(0))
            nam<-"Sheet1"
            if(row<=length(input$combination))
            {
              df<-as.data.frame(result[[row]][[col]])
              df_final<- df[order(df$padj),]
              colnames(df_final)[1]<-"Overall mean"
              for (i in 8:length(colnames(df_final)))
              {
                colnames(df_final)[i]<-paste(colnames(df_final)[i],"mean")
              }
              nam<-"Sheet 1"
              condition<-combo()[[row]]
              condition<-str_replace_all(condition,"[^[:alnum:]]",".")
              if(col==1) nam<-paste('Up regulated TF for ',condition)
              else if(col==2) nam<-paste('Down regulated TF for ',condition)
              else nam<-paste('All DE TF for ',condition)
            }
            else{
              df_final<-result[[row]][[4]]
              cluster_info<-as.data.frame(CoCena()$cluster_calc()[CoCena()$cluster_calc()$cluster_included=="yes",])
              nam<-paste('ANOVA table for TF in module ',cluster_info$color[row])
            }
            write.csv(df_final, file)
            
          }
        }
      )
    }
  })
  return(list(de_genes=reactive({DE_TF()})))
}
