source("functions.R")

Kegg_module_UI<-function(id)
{
  ns<-NS(id)
  tagList(
    fluidRow(column(10,bsAlert("OthersAnchor"))),
     bscols(widths = 10,div(style="height: 15px;",width = '200px')),
     a("Click to be directed to KEGG organism database", href="http://www.genome.jp/kegg/catalog/org_list.html", target="_blank"),
     bscols(widths = 10,div(style="height: 15px;",width = '200px')), 
    fluidRow(column(10,DT::dataTableOutput(ns("Enriched_kegg")))),
    br(),
    hr(),
    br(),
    fluidRow(
      column(1,
             selectInput(ns("datachoice9")  ,label = h5("Select Data Type"), 
                         choices = list("Excel" = 1, "CSV" = 2),
                         selected = 1)),
      column(1, 
             br(),
             br(),
             downloadButton(ns('download_Enriched_Kegg_Table'), 'Download Enriched Kegg Table'))),
    DT::dataTableOutput(ns("filtered_Kegg")),
   br(),
   br(),
   hr(),
   br(),
    uiOutput(ns("plot_category")),
   br(),
    fluidRow(column(12,

                    downloadButton(ns('download_kegg_plot'), 'Download Plot'),
                    plotOutput(ns("kegg"))),
             column(8,
                    uiOutput(ns("op")),
                    uiOutput(ns("op_an")),
                    uiOutput(ns("limit_fc")),
                    downloadButton(ns('download_kegg'), 'Download Plot'),
                    plotOutput(ns("image2"))
              ))
  )
}

Kegg_module<-function(input,output,session,DE_genes,
                      organism,dds.fc,combination,CoCena,anova_table,orgDB)
{

  combo<-combination()
  print(combo())
  num<-length(combo())
  #Compute the KEGG pathway based on a list for a list of DE genes(Uses function enrichKEGG from clusterprofiler)
  #Construct  a matrix where row->comparison A vs B, C vs D .etc
  # columns (up regulated pathways, down regulated pathways)
  #Loop through a similar matrix generated by reactive DE_genes)
  #Filter KEGG pathways for each element in the matrix generated by reactive DE_genes
  print("inside kegg line 39")
  result_de<-DE_genes()
  Enriched_Kegg<-reactive({
    if (organism() != "Others"){
      
    closeAlert(session,"Others2")
    num<-length(combo())
    if(!is.null(CoCena()))
    {
      cluster_info<-as.data.frame(CoCena()$cluster_calc()[CoCena()$cluster_calc()$cluster_included=="yes",])
        enrichment_main("kegg",result_de(),organism(),dds.fc(),
                    num,cluster_info,NULL,orgDB())
      
    }
    else
    {
      combo<-combination()
      num<-length(combo())
      enrichment_main("kegg",result_de(),organism(),dds.fc(),
                      num,NULL,NULL,orgDB())
    }
    } else {
      createAlert(session, "OthersAnchor", "Others2", title = "Error",
                  content = "This module is not available for organism 'Others'")
    }  
  })
  
  #Display summary of KEGG pathways identified for the comparisons
  output$Enriched_kegg <- DT::renderDataTable({
    
      result<-Enriched_Kegg()[[1]]
      rows<-num

      res<-NULL
      
      if(!is.null(CoCena()))
      {
          cluster_info<-as.data.frame(CoCena()$cluster_calc()[CoCena()$cluster_calc()$cluster_included=="yes",])
          entry<-c(as.vector(combo()), as.vector(cluster_info$color))
          rows<-length(entry)
          res<-data.frame(matrix(NA, nrow = rows, ncol = 3))
          colnames(res)<-c('Enriched Kegg pathways for Up-reg genes','Enriched Kegg pathways for Down-reg genes', 'Enriched Kegg pathways for included genes')
          rownames(res)<-lapply(1:rows, function(i) {
            entry[[i]]
            
          })
          for(i in 1:length(combo()))
          {
            res[i,1]<-nrow(as.data.frame(result[[i]][[1]]))
            res[i,2]<-nrow(as.data.frame(result[[i]][[2]]))
            res[i,3]<-0
          }

          for(i in (1+length(combo())):(nrow(cluster_info)+length(combo())))
          {
            res[i,1:2]<-0
            res[i,3]<-length(result[[i]][[3]])
            
          }
        
      }
      else{
        res<-data.frame(matrix(NA, nrow = length(combo()), ncol = 2))
        rownames(res)<-lapply(1:length(combo()), function(i) {
          combo()[[i]]

        })
        colnames(res)<-c('Enriched Kegg pathways for Up-reg genes','Enriched Kegg pathways for Down-reg genes')

        for(i in 1:length(combo()))
        {
          res[i,1]<-nrow(as.data.frame(result[[i]][[1]]))
          res[i,2]<-nrow(as.data.frame(result[[i]][[2]]))
        }
      }

      DT::datatable(res,class = 'cell-border stripe',
                    selection = list(mode='single',target = 'cell'),
                    extensions = list('Scroller'=NULL,'Buttons'=NULL),
                    options = list(deferRender = TRUE,scrollX = TRUE,scrollY = 150,scroller = TRUE,dom = 'Bfrtip',
                                   buttons = list()),
                    
                    escape = FALSE
      )
    
  })

  #Display kegg pathway for the selected comparison
  
observeEvent(input$Enriched_kegg_cell_clicked,{

    selected <- input$Enriched_kegg_cells_selected
    row<-selected[1]
    col<-selected[2]
    
    if(length(selected)>0){
      
      output$filtered_Kegg <- DT::renderDataTable({
        result<-Enriched_Kegg()[[1]]
        df<-as.data.frame(result[[row]][[col]])
        DT::datatable(df,class = 'cell-border stripe',
                      selection = list(mode='single',target = 'row'),
                      extensions = list('Scroller'=NULL,'Buttons'=NULL),
                      options = list(deferRender = TRUE,scrollX = TRUE,scrollY = 150,scroller = TRUE,dom = 'Bfrtip',
                                     buttons = list()))
        
        
        
      })
      
      #Input to display selected kegg pathway
      output$op<-renderUI({
        if(row<=num)
        {
          radioButtons(session$ns("de"), "Choice of genes to be colored", choices = c("ANOVA", "DE"))
        }
        
      })
    output$op_an<-renderUI({
      combo<-combination()
      num<-length(combo())
        if(row>num)
        {
          
          if(!is.null(combo()))
          {

            comb<-lapply(1:num, function(i) {
              combo()[[i]]

            })
            
            checklist<-list()
            for (i in seq_along(comb)) {
              checklist[[comb[[i]]]] = i
            }
            selectInput(session$ns("ANOVA_choice"),label = h5("Choose comparison") ,
                        choices = checklist,selected = 1)
          }
        }
        
      })
      
      #Display kegg pathway plot for the pathway selected  
   observeEvent(input$filtered_Kegg_rows_selected,{

        sel <- input$filtered_Kegg_rows_selected
        result<-Enriched_Kegg()[[1]]
        a_tab<-anova_table()[,-c(2,3)]
        temp<-8
        
        #get the organism
        org <- orgDB()
        species <- search_kegg_organism(organism(), ignore.case = T)[1,1]
        
        reg <- AnnotationDbi::select(org,rownames(a_tab),"ENTREZID","SYMBOL",multiVals="first")
        idx <- match(rownames(a_tab), reg$SYMBOL)
        a_tab$entrez<-reg$ENTREZID[idx]
        dds<-colData(dds.fc())$condition
        
        geneList<-reactive({
          genList<-NULL
          res<-Enriched_Kegg()[[3]]
          df<-as.data.frame(result[[row]][[col]])
          
          if((row<=num)&&(input$de=="DE"))
          {
            selected <- input$Enriched_kegg_cells_selected
            row<-selected[1]
            col<-selected[2]
            genList<-res[[row]][[col]]
            
          }
          else if((row<=num)&&(input$de=="ANOVA"))
          {
            temp<-3+length(unique(dds))+1+((row-1)*6)
            idx_wo_na<-which(!is.na(reg$ENTREZID[idx]))
            gList<-as.data.frame(matrix(NA,nrow=length(reg$ENTREZID[idx_wo_na]),ncol=2))
            colnames(gList)<-c("entrez","foldchange")
            gList$foldchange<-c(as.numeric(a_tab[idx_wo_na,temp]))
            gList$entrez<-c(as.list(reg$ENTREZID[idx_wo_na]))
            genList<-gList$foldchange
            names(genList)<-gList$entrez
            na.omit(genList)

          }
          else if(!is.null(as.numeric(input$ANOVA_choice))){
            i<-as.numeric(input$ANOVA_choice)
            temp<-3+length(unique(dds))+1+((i-1)*6)#index of foldchanges of all comparisons
            idx_wo_na<-which(!is.na(a_tab$entrez))
            gList<-as.data.frame(matrix(NA,nrow=length(reg$ENTREZID[idx_wo_na]),ncol=2))
            colnames(gList)<-c("entrez","foldchange")
            gList$foldchange<-c(as.numeric(a_tab[idx_wo_na,temp]))
            gList$entrez<-c(as.list(reg$ENTREZID[idx_wo_na]))
            genList<-gList$foldchange
            names(genList)<-gList$entrez
            na.omit(genList)
          }
          return(list(genList,df$ID[sel]))
        })

        #get the anova table
        if(length(geneList()[[1]])>1 && !is.null(geneList()[[1]]))
        {
          output$limit_fc<-renderUI({
            textInput(session$ns("limit_fc"), "Enter foldchange limit", value = max(abs(geneList()[[1]])), width = NULL, placeholder = NULL)
          })

          output$image2 <- renderImage({
            hsa04110 <- pathview(gene.data  = geneList()[[1]],
                                 pathway.id = geneList()[[2]],
                                 species    = species,
                                 limit      = list(gene=as.numeric(input$limit_fc), cpd=1))
            print(paste(geneList()[[2]],".pathview.png",sep = ""))
            file<-list.files(pattern=paste(geneList()[[2]],".pathview.png",sep=""), full.names=TRUE)
            print(file)
            return(list(
              src = file,
              contentType = "image/png"
            ))
            
            
          }, deleteFile = TRUE)
          
        }
    })  
      #download button
output$download_Enriched_Kegg_Table <- downloadHandler(
        
        filename = function() 
        {
          if(as.numeric(input$datachoice9==1)){
          condition <-combo()[[row]]
          if(col==1) paste('Up regulated Kegg for ',condition,'.xlsx')
          else if(col==2) paste('Down regulated Kegg for ',condition,'.xlsx')
          else if(col==3) paste('regulated Kegg for ',condition,'.xlsx')
          }
          else {
            condition <-combo()[[row]]
            if(col==1) paste('Up regulated Kegg for ',condition,'.csv')
            else if(col==2) paste('Down regulated Kegg for ',condition,'.csv')
            else if(col==3) paste('regulated Kegg for ',condition,'.csv')
          }
        },
        content = function(file) {
          #sort by adjusted p value.
          result<-Enriched_Kegg()[[1]]
          
          df<-as.data.frame(result[[row]][[col]])
          
          nam<-"Sheet 1"
          condition <-combo()[[row]]
          condition<-str_replace_all(condition,"[^[:alnum:]]",".")
          if(col==1) nam<-paste('Up regulated Kegg for ',condition)
          else if(col==2) nam<-paste('Down regulated Kegg for ',condition)
          else if(col==3) nam<-paste('regulated Kegg for ',condition)

          if(as.numeric(input$datachoice9==1)){
            M <- as.matrix(df)
            wb <- createWorkbook()
            addWorksheet(wb, sheetName = "Kegg table")
            writeData(wb = wb, sheet = 1, x = M, colNames = T, rowNames = T)
            saveWorkbook(wb, file)

          }
          else {
            write.csv(df, file)
          }
          
        }
        
      )

      
output$plot_category<-renderUI({
        textInput(session$ns("category"),label = h6("Enter number of categories to display"), 
                  value = "10") 
      })

#Display barplot of top 10 kegg pathway identified for selected comparison
keggplot<-reactive({
  result<-Enriched_Kegg()[[2]] #obj
  res<-Enriched_Kegg()[[1]]
  if(nrow(res[[row]][[col]]) == 0){
    warning("No Data available for plotting")
  }
  else if(nrow(res[[row]][[1]]) == 0 && nrow(res[[row]][[2]] != 0)){
   enriched_plot <- enrichment_plot("kegg",result,res,row,1,input$category,"")
  }
  else{
   enriched_plot <- enrichment_plot("kegg",result,res,row,col,input$category,"")
  }
  enriched_plot
})

output$kegg<- renderPlot({
  keggplot()
})

output$download_kegg_plot <- downloadHandler(
  filename = function()
  {
    condition <-combo()[[row]]
    if(col==1) paste(input$plot_k,' of Up regulated kegg for ',condition,'.svg')
    else if(col==2) paste(input$plot_k,' of Down regulated kegg for ',condition,'.svg')
    else if(col==3) paste(input$plot_k,' of regulated kegg for ',condition,'.svg')
  },
  content = function(file) {
    print(file)
    ggsave(file,keggplot())#,width=800, height=500

  })
    }
})
return(list(
       Enriched_Kegg_table=reactive({Enriched_Kegg()[[1]]}),
       Enriched_Kegg_obj=reactive({Enriched_Kegg()[[2]]})
)
       )
}
