source("gene_count_module.R")
source("functions.R")
#####################################transcription factor prediction(primo)##########################
#Compute the Transcription factor(Uses primo function)
#Construct  a matrix where row->comparison A vs B, C vs D .etc
# columns (up regulated genes, down regulated genes, all DE genes)
#Loop through a similar matrix generated by reactive DE_genes)
#Filter TF for each element in the matrix generated by reactive DE_genes

predicted_TF_module_UI<-function(id)
{
  ns<-NS(id)
  tagList(
    fluidRow(column(10,bsAlert("Anchor1"))),
    br(),
    br(),
    fluidRow(column(2,textInput(ns("topTF"), label = "Choose the number of top transcription factors to be displayed:",
                                value = "20"),
                    actionButton(ns("predicted"), "Go!"))),
    br(),
    fluidRow(column(10,DT::dataTableOutput(ns("predicted_TF")))),
    br(),
    br(),
    hr(),
    fluidRow(column(10,DT::dataTableOutput(ns("All_predicted_TF")))),
    br(),
    br(),
    hr(),
    radioButtons(ns("lfc_pred_TF"), "Show log2 foldchange?:", choices = c("Yes", "No"),selected = "No"),
    fluidRow(
      column(1,
             selectInput(ns("datachoice7")  ,label = h5("Select Data Type"), 
                         choices = list("Excel" = 1, "CSV" = 2),
                         selected = 1)),
      column(1, 
             br(),
             br(),
             downloadButton(ns('download_DE_pred_TF_Table'), 'Download predicted TF Table'))),

    DT::dataTableOutput(ns("filtered_predicted_TF")),
    gene_count_module_UI(ns("module4"))
  )
}
predicted_TF_module<-function(input,output,session,
                              DE_genes,dds.fc,anova_table,
                              combination,conchoice,CoCena,
                              organism,normal,batch_choice,batch_corrected,dataset)
{

predicted_TF<-eventReactive(input$predicted,{
  if(!(organism() %in% c("Anopheles gambiae",
                     "Arabidopsis thalina",
                     "Canis familiaris",
                     "K-12",
                     "Sakai",
                     "Plasmodium falciparum",
                     "Others"))){
    closeAlert(session, "Error")
    print(is.null(CoCena()))
  if(!is.null(CoCena())){ 
    cluster_info<-as.data.frame(CoCena()$cluster_calc()[CoCena()$cluster_calc()$cluster_included=="yes",])
    predicted <- TF_prediction_ChEA3(DE_genes(), dds.fc(), anova_table(),combination(), conchoice(),cluster_info, organism(), dataset(), as.numeric(input$topTF))
    }
    else predicted <- TF_prediction_ChEA3(DE_genes(), dds.fc(), anova_table(),combination(), conchoice(), NULL, organism(), dataset(), as.numeric(input$topTF))
    predicted
  }else {
    createAlert(session, "Anchor1", "Error", title = "Oops!",
                content = "Transcription factor prediction is not available for the chosen organism")
  }
})

  
output$predicted_TF <- DT::renderDataTable({
  if(!is.null(DE_genes())){
    
    result<-predicted_TF()[[2]]

    combo<-combination()

    rows<-length(combo)

    res<-data.frame(matrix(NA, nrow = length(combo), ncol = 3))
    if(!is.null(CoCena()))
    {
        combo<-combination()
        cluster_info<-as.data.frame(CoCena()$cluster_calc()[CoCena()$cluster_calc()$cluster_included=="yes",])
        entry<-c(as.vector(combo), as.vector(cluster_info$color))

        rows<-length(entry)
        
        res<-data.frame(matrix(NA, nrow = rows, ncol = 3))
        colnames(res)<-c('Predicted TF for Up-reg genes','Predicted TF for Down-reg genes','Predicted TF for All genes')

        rownames(res)<-lapply(1:rows, function(i) {
          unlist(entry[i])
          
        })
        for(i in 1:length(combo))
        {

          res[i,1]<-nrow(as.data.frame(result[[i]][[1]]))
          res[i,2]<-nrow(as.data.frame(result[[i]][[2]]))
          res[i,3]<-nrow(as.data.frame(result[[i]][[3]]))
        }
        
        for(i in 1:nrow(cluster_info))
        {

          res[length(combo)+i,1:2]<-0
          res[length(combo)+i,3]<-nrow(as.data.frame(result[[length(combo)+i]][[3]]))
          
        }
      
    }
    else{
      combo<-combination()
      rownames(res)<-lapply(1:length(combo), function(i) {

        combo[[i]]
        
      })
      colnames(res)<-c('Predicted TF for Up-reg genes','Predicted TF for Down-reg genes','Predicted TF for All genes')

      for(i in 1:length(combo))
      {
        res[i,1]<-nrow(as.data.frame(result[[i]][[1]]))
        res[i,2]<-nrow(as.data.frame(result[[i]][[2]]))
        res[i,3]<-nrow(as.data.frame(result[[i]][[3]]))
      }
    }

    DT::datatable(res,class = 'cell-border stripe',
                  selection = list(mode='single',target = 'cell'),
                  extensions = list('Scroller'=NULL,'Buttons'=NULL),
                  options = list(deferRender = TRUE,scrollX = TRUE,scrollY = 150,scroller = TRUE,dom = 'Bfrtip',
                                 buttons = list(list(extend = 'collection',buttons = c('csv', 'excel', 'pdf'),
                                                             text = 'Download table'))),
                  
                  escape = FALSE
    )
  }
})

observeEvent(input$predicted_TF_cell_clicked,{

  selected <- input$predicted_TF_cells_selected
  row<-selected[1]

  col<-selected[2]

  if(length(selected)>0){
    output$All_predicted_TF<- DT::renderDataTable({

      result<-predicted_TF()[[2]]
      df<-as.data.frame(result[[row]][[col]])

      colnames(df)<-c("TF", "Score", "Targets")
      DT::datatable(df,class = 'cell-border stripe',
                    selection = list(mode='single',target = 'row'),
                    extensions = list('Scroller'=NULL,'Buttons'=NULL),
                    options = list(deferRender = TRUE,scrollX = TRUE,scrollY = 150,scroller = TRUE,dom = 'Bfrtip',
                                   buttons = list(list(extend = 'collection',buttons = c('csv', 'excel', 'pdf'),
                                                               text = 'Download'))))
    })

    output$filtered_predicted_TF <- DT::renderDataTable({

      result<-predicted_TF()[[1]]
      df<-as.data.frame(result[[row]][[col]])
      idx_all<-predicted_TF()[[3]]
      idx<-idx_all[[row]][[col]]
      if(input$lfc_pred_TF =="No")
      {
        names<-colnames(df)
        id<-grep("log2FoldChange",names)
        df=df[,-id]
      }

      gene_names<-rownames(df)
      df_final<-cbind(gene_names,df)
      colnames(df_final)[1]<-'Gene names'

      de_genes<-gene_names[idx]
      dat<-DT::datatable(df_final,class = 'cell-border stripe',
                         selection = list(mode='single',target = 'row'),
                         extensions = list('Scroller'=NULL,'Buttons'=NULL),
                         options = list(deferRender = TRUE,scrollX = TRUE,scrollY = 150,scroller = TRUE,dom = 'Bfrtip',
                                        buttons = list()))
      if(!is.null(de_genes) || !identical(character(0),de_genes))
        dat%>% formatStyle('Gene names',target = 'row',backgroundColor =styleEqual(de_genes,rep('yellow',length(de_genes))))

      dat
    })
  
    ###plotcounts of gene
    #display filtered ANOVA table for the selcted comparisons
    #display boxplot of gene selcted in the fitered ANOVA table
    observeEvent(input$filtered_predicted_TF_rows_selected,{
      #get the row  number of the gene clicked

      selected_row <- input$filtered_predicted_TF_rows_selected

      #get the normalized data
      full_data<-normal()

      #get the DE table where we clicked the gene

      selected <- input$predicted_TF_cells_selected
      row<-selected[1]

      col<-selected[2]

      if(length(selected)>0)
      {
        result<-predicted_TF()[[1]]
        df_final<-as.data.frame(result[[row]][[col]])
        #get the gene
        an_gene<-rownames(df_final)[selected_row]
        counts<-as.vector(full_data[which(an_gene %in% rownames(full_data)),])
        cond<-as.vector(colData(dds.fc()[[1]])[,as.numeric(conchoice())])
        library('data.table')
        df<-data.frame(counts,cond)
        colnames(df)<-c('count','condition')

        batch<-batch_choice()
        if(as.numeric(batch)==1) callModule(gene_count_module,"module4",NULL,reactive({dds.fc()[[1]]}),reactive({an_gene}))
        else
          {
            idx<-which(rownames(batch_corrected()) %in% an_gene)
            callModule(gene_count_module,"module4",batch_corrected()[idx,],reactive({dds.fc()[[1]]}),reactive({an_gene}))
          }
      }
      })
    
    #download button
    output$download_DE_pred_TF_Table <- downloadHandler(
      
      filename = function() 
      {
        if (as.numeric(input$datachoice7==1)){
        combo<-combination()
        condition<-combo[[row]]
        if(col==1) paste('Up regulated predicted TF for ',condition,'.xlsx')
        else if(col==2) paste('Down regulated predicted TF for ',condition,'.xlsx')
        else paste('All DE predicted TF for ',condition,'.xlsx')
        }
        else {
          combo<-combination()
          condition<-combo[[row]]
          if(col==1) paste('Up regulated predicted TF for ',condition,'.csv')
          else if(col==2) paste('Down regulated predicted TF for ',condition,'.csv')
          else paste('All DE predicted TF for ',condition,'.csv')
        }
      },
      content = function(file) {
        if (as.numeric(input$datachoice7==1)){
        #sort by adjusted p value.
        print('heyho')
        result<-predicted_TF()[[1]]
        df<-as.data.frame(result[[row]][[col]])

        df_final<- df[order(df$padj),]
        colnames(df_final)[1]<-"Overall mean"
        for (i in 8:length(colnames(df_final)))
        {
          colnames(df_final)[i]<-paste(colnames(df_final)[i],"mean")
        }
        nam<-"Sheet 1"
        combo<-combination()
        condition<-combo[[row]]
        condition<-str_replace_all(condition,"[^[:alnum:]]",".")
        if(col==1) nam<-paste('Up regulated Kegg for ',condition)
        else if(col==2) nam<-paste('Down regulated Kegg for ',condition)
        else if(col==3) nam<-paste('regulated Kegg for ',condition)
        
        M <- as.matrix(df_final)
        wb <- createWorkbook()
        addWorksheet(wb, sheetName = "predicted TF table")
        writeData(wb = wb, sheet = 1, x = M, colNames = T, rowNames = T)
        saveWorkbook(wb, file)

        }
        else {
          #sort by adjusted p value.
          result<-predicted_TF()[[1]]
          df<-as.data.frame(result[[row]][[col]])
          df_final<- df[order(df$padj),]
          colnames(df_final)[1]<-"Overall mean"
          for (i in 8:length(colnames(df_final)))
          {
            colnames(df_final)[i]<-paste(colnames(df_final)[i],"mean")
          }

          nam<-"Sheet 1"
          combo<-combination()
          condition<-combo[[row]]
          condition<-str_replace_all(condition,"[^[:alnum:]]",".")
          if(col==1) nam<-paste('Up regulated Kegg for ',condition)
          else if(col==2) nam<-paste('Down regulated Kegg for ',condition)
          else if(col==3) nam<-paste('regulated Kegg for ',condition)
          write.csv(df_final, file)
        }
      }
      
    )
  }
})

}