source("gene_count_module.R")
#####################################transcription factor prediction(primo)##########################
#Compute the Transcription factor(Uses primo function)
#Construct  a matrix where row->comparison A vs B, C vs D .etc
# columns (up regulated genes, down regulated genes, all DE genes)
#Loop through a similar matrix generated by reactive DE_genes)
#Filter TF for each element in the matrix generated by reactive DE_genes

predicted_TF_module_UI<-function(id)
{
  ns<-NS(id)
  tagList(
    fluidRow(column(10,bsAlert("Anchor1"))),
    br(),
    br(),
    fluidRow(column(2,textInput(ns("topTF"), label = "Choose the number of top transcription factors to be displayed:",
                                value = "20"),
                    actionButton(ns("predicted"), "Go!"))),
    br(),
    fluidRow(column(10,DT::dataTableOutput(ns("predicted_TF")))),
    br(),
    br(),
    hr(),
    fluidRow(column(10,DT::dataTableOutput(ns("All_predicted_TF")))),
    br(),
    br(),
    hr(),
    radioButtons(ns("lfc_pred_TF"), "Show log2 foldchange?:", choices = c("Yes", "No"),selected = "No"),
    fluidRow(
      column(1,
             selectInput(ns("datachoice7")  ,label = h5("Select Data Type"), 
                         choices = list("Excel" = 1, "CSV" = 2),
                         selected = 1)),
      column(1, 
             br(),
             br(),
             downloadButton(ns('download_DE_pred_TF_Table'), 'Download predicted TF Table'))),
    
    
    #downloadButton(ns('download_DE_pred_TF_Table'), 'Download full Data'),
    DT::dataTableOutput(ns("filtered_predicted_TF")),
    gene_count_module_UI(ns("module4"))
    # uiOutput("plot_option_gene_predicted_TF"),
    # downloadButton('download_gene_predicted_tf', 'Download plot'),
    # plotOutput("gene_plot_predicted_TF")
    # 
  )
}
predicted_TF_module<-function(input,output,session,
                              DE_genes,dds.fc,anova_table,
                              combination,conchoice,wgcna_output,
                              organism,normal,batch_choice,batch_corrected,dataset)
{

predicted_TF<-reactive({
  if(!(organism() %in% c("Anopheles gambiae",
                     "Arabidopsis thalina",
                     "Canis familiaris",
                     "K-12",
                     "Sakai",
                     "Plasmodium falciparum",
                     "Others"))){
    closeAlert(session, "Error")
  
  # Create a Progress object
  progress <- shiny::Progress$new()
  # Make sure it closes when we exit this reactive, even if there's an error
  on.exit(progress$close())
  
  #get all de genes
  result<-DE_genes()
  combo<-combination()

  progress$set(message = "Processing Data", value = 0)
  
  Enriched_dt<-list()
  All_pred_tf<-list()
  All_idx<-list()
  topTF_list<-list()
  
  #########preparing the anova table in the order as output#########
  a_tab<-anova_table()[,-c(2,3)]
  cond<-unique(colData(dds.fc()[[1]])[,as.numeric(conchoice())])

  c<-colnames(a_tab)

  temp<-as.vector(c[4:(3+length(cond))])
  temp2<-as.vector(c[(length(cond)+4):length(c)])

  all_genes=a_tab[,c(temp,c[2],c[3],temp2,c[1])]
  

  
  ##################################################################
  for(i in 1:length(combo()))
  {
    dt<-list()
    All_pred<-list()
    idx_pred<-list()
    tf_list<-list()
    for(j in 1:3)
    {

      res<-as.data.frame(result()[[i]][[j]])

      TFs<-NULL
      TF_table<-NULL
      if(nrow(res)!=0)
      {
        genes<-res[,1]
        df<-res[,-1]
        rownames(df)<-genes  
        if(organism() == "Homo sapiens"){
          url = "https://amp.pharm.mssm.edu/chea3/api/enrich/"
          encode = "json"
          payload = list(query_name = "myQuery", gene_set = genes)
          
          #POST to ChEA3 server
          response = POST(url = url, body = payload, encode = encode)
          json = httr::content(response, as = "text")
          
          #results as list of R dataframes
          TF_table = fromJSON(json)
          TF_table <- TF_table$`Integrated--meanRank`
          
          # extract those from meanRank since meanRank scored as best method:
          TF_table <- TF_table[,c("TF", "Score", "Overlapping_Genes")]
          TF_table$Score <- as.numeric(TF_table$Score)
          if (as.numeric(input$topTF) < nrow(TF_table)) TF_table = TF_table[1:as.numeric(input$topTF),]
          TFs <- as.character(TF_table$TF)
          

        } else if(organism() == "Mus musculus"){
            url = "https://amp.pharm.mssm.edu/chea3/api/enrich/"
            encode = "json"
            payload = list(query_name = "myQuery", gene_set = genes)
            
            #POST to ChEA3 server
            response = POST(url = url, body = payload, encode = encode)
            json = httr::content(response, as = "text")
            
            #results as list of R dataframes
            TF_table = fromJSON(json)
            TF_table <- TF_table$`Integrated--meanRank`
            
            # extract those from meanRank since meanRank scored as best method:
            TF_table <- TF_table[,c("TF", "Score", "Overlapping_Genes")]
            TF_table$Score <- as.numeric(TF_table$Score)
            if(is.null(input$topTF)){
            if(20 < nrow(TF_table)) TF_table = TF_table[1:20,]
            }
            else if (as.numeric(as.numeric(input$topTF)) < nrow(TF_table)) TF_table = TF_table[1:as.numeric(input$topTF),]

            
            human = useMart("ENSEMBL_MART_ENSEMBL", dataset = "hsapiens_gene_ensembl")
            mouse = useMart("ENSEMBL_MART_ENSEMBL", dataset = "mmusculus_gene_ensembl")
            
            mouse_gene = getLDS(attributes = c("hgnc_symbol"), filters = "hgnc_symbol", values = TF_table$TF , mart = human, attributesL = c("mgi_symbol"), martL = mouse, uniqueRows=T)
            TFs <- mouse_gene[, 2]

            
            
          } else {
          createAlert(session, "Anchor1", "Warning", title = "Warning!",
                      content = "For the chosen organism human transcription factors are returned")
          human = useMart("ENSEMBL_MART_ENSEMBL", dataset = "hsapiens_gene_ensembl")
          chosen_organism = useMart("ENSEMBL_MART_ENSEMBL", dataset = dataset())
          
          human_gene <- getLDS(attributes = c("external_gene_name"), filters = "external_gene_name", values = genes , mart = chosen_organism, attributesL = c("hgnc_symbol"), martL = human, uniqueRows=T)
          genes <- human_gene[, 2]
          
          url = "https://amp.pharm.mssm.edu/chea3/api/enrich/"
          encode = "json"
          payload = list(query_name = "myQuery", gene_set = genes)
          
          #POST to ChEA3 server
          response = POST(url = url, body = payload, encode = encode)
          json = httr::content(response, as = "text")
          
          #results as list of R dataframes
          TF_table = fromJSON(json)
          TF_table <- TF_table$`Integrated--meanRank`
          
          # extract those from meanRank since meanRank scored as best method:
          TF_table <- TF_table[,c("TF", "Score", "Overlapping_Genes")]
          TF_table$Score <- as.numeric(TF_table$Score)
          
          if (as.numeric(input$topTF) < nrow(TF_table)) TF_table = TF_table[1:as.numeric(input$topTF),]
          TFs <- TF_table$TF
          
          chosen_organism_gene = getLDS(attributes = c("hgnc_symbol"), filters = "hgnc_symbol", values = TFs , mart = human, attributesL = c("external_gene_name"), martL = chosen_organism, uniqueRows=T)
          TFs <- chosen_organism_gene[, 2]
          
        }
        if(!is.null(TFs))
        {
          tf_list[[length(tf_list)+1]]<-as.data.frame(cbind(TF=TFs,Score=as.numeric(TF_table$Score)))
          tf_list[[length(tf_list)]] <- tf_list[[length(tf_list)]][order(tf_list[[length(tf_list)]]$Score, decreasing = T),]
          dt[[length(dt)+1]]<-all_genes[as.character(rownames(all_genes)) %in% TFs,]
          All_pred[[length(All_pred)+1]]<-TF_table#TFs
          de_genes_pred_idx<- all_genes$name[as.character(rownames(all_genes)) %in% rownames(res)]
          idx_pred[[length(idx_pred)+1]]<-de_genes_pred_idx

          
        }
        else
        {
          tf_list[[length(tf_list)+1]]<-NULL
          dt[[length(dt)+1]]<-NULL
          All_pred[[length(All_pred)+1]]<-NULL
          idx_pred[[length(idx_pred)+1]]<-NULL
        }
      }
      else
      {
        tf_list[[length(tf_list)+1]]<-NULL
        dt[[length(dt)+1]]<-NULL 
        All_pred[[length(All_pred)+1]]<-NULL
        idx_pred[[length(idx_pred)+1]]<-NULL
      }
    }

    topTF_list[[i]]<-tf_list
    Enriched_dt[[i]]<-dt
    All_pred_tf[[i]]<-All_pred
    All_idx[[i]]<-idx_pred
    print("TF_table")
    print(str(All_pred_tf))
    print("topTF_list")
    print(str(topTF_list))
  }
  if(!is.null(wgcna_output()))
  {
    if((length(wgcna_output()$modules())>0))
    {
      mod<- wgcna_output()$modules()
      modules<-as.data.frame(table(mod))
      colnames(modules)<-c("Var1","number")
      WGCNA_matrix<-wgcna_output()$WGCNA_matrix()
      for(i in 1:nrow(modules))
      {
        
        print('freq')
        print(modules$Freq[i])
        
        idx_w<-which(mod==modules$Var1[i])
        DEG<-colnames(WGCNA_matrix)[idx_w]
        if(!identical(character(0),DEG))
        {
          if(organism() %in% c("Homo sapiens", "Mus musculus"))
          {
            url = "https://amp.pharm.mssm.edu/chea3/api/enrich/"
            encode = "json"
            payload = list(query_name = "myQuery", gene_set = DEG)
            
            #POST to ChEA3 server
            response = POST(url = url, body = payload, encode = encode)
            json = httr::content(response, as = "text")
            
            #results as list of R dataframes
            TF_table = fromJSON(json)
            TF_table <- TF_table$`Integrated--meanRank`
            
            # extract those from meanRank since meanRank scored as best method:
            TF_table <- TF_table[,c("TF", "Score", "Overlapping_Genes")]
            TF_table$Score <- as.numeric(TF_table$Score)
            TF_table <- TF_table[TF_table$Score <= 100,]
            TFs <- TF_table$TF
          }
          else
          {
            human = useMart("ENSEMBL_MART_ENSEMBL", dataset = "hsapiens_gene_ensembl")
            drosophila = useMart("ENSEMBL_MART_ENSEMBL", dataset = "dmelanogaster_gene_ensembl")
            
            human_gene <- getLDS(attributes = c("external_gene_name"), filters = "external_gene_name", values = DEG , mart = drosophila, attributesL = c("hgnc_symbol"), martL = human, uniqueRows=T)
            DEG <- human_gene[, 2]
            
            url = "https://amp.pharm.mssm.edu/chea3/api/enrich/"
            encode = "json"
            payload = list(query_name = "myQuery", gene_set = DEG)
            
            #POST to ChEA3 server
            response = POST(url = url, body = payload, encode = encode)
            json = httr::content(response, as = "text")
            
            #results as list of R dataframes
            TF_table = fromJSON(json)
            TF_table <- TF_table$`Integrated--meanRank`
            
            # extract those from meanRank since meanRank scored as best method:
            TF_table <- TF_table[,c("TF", "Score", "Overlapping_Genes")]
            TF_table$Score <- as.numeric(TF_table$Score)
            
            TF_table <- TF_table[TF_table$Score <= 100,]
            TFs <- TF_table$TF
            
            fly_gene = getLDS(attributes = c("hgnc_symbol"), filters = "hgnc_symbol", values = TFs , mart = human, attributesL = c("external_gene_name"), martL = drosophila, uniqueRows=T)
            TFs <- fly_gene[, 2]
          } 
          
          if(!is.null(TFs))
          {

            d<-data.frame(matrix(NA, nrow = 0, ncol = 1))
            Enriched_dt[[length(Enriched_dt)+1]]<-list(NULL,NULL,all_genes[which(rownames(all_genes) %in% TFs),])
            All_pred_tf[[length(All_pred_tf)+1]]<-list(d,d,TF_table)#TFs
            anova_genes<-rownames(all_genes[which(rownames(all_genes) %in% TFs),])
            de_genes_pred_idx<-which(anova_genes %in% DEG)
            All_idx[[length(All_idx)+1]]<-list(NULL,NULL,NULL)#de_genes_pred_idx)
            
          }
          else
          {
            d<-data.frame(matrix(NA, nrow = 0, ncol = 1))
            Enriched_dt[[length(Enriched_dt)+1]]<-list(NULL,NULL,NULL)
            All_pred_tf[[length(All_pred_tf)+1]]<-list(d,d,d)
            All_idx[[length(All_idx)+1]]<-list(NULL,NULL,NULL)
          }
          
          
        }
        else
        {
          d<-data.frame(matrix(NA, nrow = 0, ncol = 1))
          Enriched_dt[[length(Enriched_dt)+1]]<-list(NULL,NULL,NULL)
          All_pred_tf[[length(All_pred_tf)+1]]<-list(d,d,d)
          All_idx[[length(All_idx)+1]]<-list(NULL,NULL,NULL)
        }
      }
      
    }
  }

  list(Enriched_dt,All_pred_tf,All_idx,topTF_list)
  }else {
    createAlert(session, "Anchor1", "Error", title = "Oops!",
                content = "Transcription factor prediction is not available for the chosen organism")
  }
})
observeEvent(input$predicted,{
  
output$predicted_TF <- DT::renderDataTable({
  if(!is.null(DE_genes())){
    
    result<-predicted_TF()[[2]]

    combo<-combination()

    rows<-length(combo())
    modules<-NULL
    WGCNA_matrix<-NULL
    res<-data.frame(matrix(NA, nrow = length(combo()), ncol = 3))
    if(!is.null(wgcna_output()))
    {
      if((length(wgcna_output()$modules())>0))
      {
        combo<-combination()
        modules<-as.data.frame(table(wgcna_output()$modules()))
        entry<-c(as.vector(combo()), as.vector(modules$Var1))

        rows<-length(entry)
        
        res<-data.frame(matrix(NA, nrow = rows, ncol = 3))
        colnames(res)<-c('Up regulated','Down regulated','Regulated')

        rownames(res)<-lapply(1:rows, function(i) {
          unlist(entry[i])
          
        })
        for(i in 1:length(combo()))
        {

          res[i,1]<-nrow(as.data.frame(result[[i]][[1]]))
          res[i,2]<-nrow(as.data.frame(result[[i]][[2]]))
          res[i,3]<-nrow(as.data.frame(result[[i]][[3]]))
        }
        
        for(i in 1:nrow(modules))
        {

          res[length(combo())+i,1:2]<-0
          res[length(combo())+i,3]<-nrow(as.data.frame(result[[length(combo())+i]][3]))
          
        }
      }
    }
    else{
      combo<-combination()
      rownames(res)<-lapply(1:length(combo()), function(i) {

        combo()[[i]]
        
      })
      colnames(res)<-c('Predicted TF for Up-reg genes','Predicted TF for Down-reg genes','Predicted TF for All genes')

      for(i in 1:length(combo()))
      {
        print(nrow(as.data.frame(result[[i]][[1]])))
        res[i,1]<-nrow(as.data.frame(result[[i]][[1]]))
        res[i,2]<-nrow(as.data.frame(result[[i]][[2]]))
        res[i,3]<-nrow(as.data.frame(result[[i]][[3]]))
      }
      print(res)
    }
    
    
    print(res)
    DT::datatable(res,class = 'cell-border stripe',
                  selection = list(mode='single',target = 'cell'),
                  extensions = list('Scroller'=NULL,'Buttons'=NULL),
                  options = list(deferRender = TRUE,scrollX = TRUE,scrollY = 150,scroller = TRUE,dom = 'Bfrtip',
                                 buttons = list(list(extend = 'collection',buttons = c('csv', 'excel', 'pdf'),
                                                             text = 'Download table'))),#I('colvis')
                  
                  escape = FALSE
    )
  }
})

observeEvent(input$predicted_TF_cell_clicked,{

  selected <- input$predicted_TF_cells_selected
  row<-selected[1]

  col<-selected[2]

  if(length(selected)>0){
    output$All_predicted_TF<- DT::renderDataTable({

      result<-predicted_TF()[[2]]
      df<-as.data.frame(result[[row]][[col]])

      colnames(df)<-c("TF", "Score", "Targets")
      DT::datatable(df,class = 'cell-border stripe',
                    selection = list(mode='single',target = 'row'),
                    extensions = list('Scroller'=NULL,'Buttons'=NULL),
                    options = list(deferRender = TRUE,scrollX = TRUE,scrollY = 150,scroller = TRUE,dom = 'Bfrtip',
                                   buttons = list(list(extend = 'collection',buttons = c('csv', 'excel', 'pdf'),
                                                               text = 'Download'))))
      
    })

  observeEvent(input$All_predicted_TF_rows_selected,{ 
 
    output$filtered_predicted_TF <- DT::renderDataTable({

      result<-predicted_TF()[[1]]
      df<-as.data.frame(result[[row]][[col]])
      selected <- input$All_predicted_TF_rows_selected
      print("selected")
      print(selected)
      row<-selected[1]
      col<-selected[2]
      
      print("result")
      print(result)
      print(row)
      print(col)

      idx_all<-predicted_TF()[[3]]

      idx<-idx_all[[row]][[col]]
      print("idx")
      print(idx)
      if(input$lfc_pred_TF =="No")
      {
        names<-colnames(df)
        id<-grep("log2FoldChange",names)
        df=df[,-id]
      }

      gene_names<-rownames(df)
      df_final<-cbind(gene_names,df)
      colnames(df_final)[1]<-'Gene names'

      de_genes<-gene_names[idx]#c('E2f1','Nfkb1')
      print("df_final")
      print(df_final)

      dat<-DT::datatable(df_final,class = 'cell-border stripe',
                         selection = list(mode='single',target = 'row'),
                         extensions = list('Scroller'=NULL,'Buttons'=NULL),
                         options = list(deferRender = TRUE,scrollX = TRUE,scrollY = 150,scroller = TRUE,dom = 'Bfrtip',
                                        buttons = list()))
      if(!is.null(de_genes) || !identical(character(0),de_genes))
        dat%>% formatStyle('Gene names',target = 'row',backgroundColor =styleEqual(de_genes,rep('yellow',length(de_genes))))
      #return(dat)
      dat
    })
})
    ###plotcounts of gene
    #display filtered ANOVA table for the selcted comparisons
    #display boxplot of gene selcted in the fitered ANOVA table
    observeEvent(input$filtered_predicted_TF_rows_selected,{
      #get which gene was clicked
      #get the row  number of the gene clicked

      #print(input$ANOVA_rows_clicked)
      selected_row <- input$filtered_predicted_TF_rows_selected

      #get the normalized data
      full_data<-normal()

      #get the DE table where we clicked the gene

      selected <- input$predicted_TF_cells_selected
      row<-selected[1]

      col<-selected[2]

      if(length(selected)>0)
      {

        result<-predicted_TF()[[1]]

        df_final<-as.data.frame(result[[row]][[col]])


        #get the gene
        an_gene<-rownames(df_final)[selected_row]

        counts<-as.vector(full_data[which(an_gene %in% rownames(full_data)),])

        cond<-as.vector(colData(dds.fc()[[1]])[,as.numeric(conchoice())])
 
        library('data.table')

        df<-data.frame(counts,cond)
        colnames(df)<-c('count','condition')

        batch<-batch_choice()
        if(as.numeric(batch)==1) callModule(gene_count_module,"module4",NULL,reactive({dds.fc()[[1]]}),reactive({an_gene}))
        else
          {
            idx<-which(rownames(batch_corrected()) %in% an_gene)

            callModule(gene_count_module,"module4",batch_corrected()[idx,],reactive({dds.fc()[[1]]}),reactive({an_gene}))
          }
      }
      })
    #download button
    output$download_DE_pred_TF_Table <- downloadHandler(
      
      filename = function() 
      {
        if (as.numeric(input$datachoice7==1)){
        #condition<-paste(combination()[[row]][1],' vs ',combination()[[row]][2])
        combo<-combination()
        condition<-combo()[[row]]
        if(col==1) paste('Up regulated predicted TF for ',condition,'.xlsx')
        else if(col==2) paste('Down regulated predicted TF for ',condition,'.xlsx')
        else paste('All DE predicted TF for ',condition,'.xlsx')
        #paste("DE genes for condition ",input$condition1," vs ",input$condition2,'.csv')
        }
        else {
          combo<-combination()
          condition<-combo()[[row]]
          if(col==1) paste('Up regulated predicted TF for ',condition,'.csv')
          else if(col==2) paste('Down regulated predicted TF for ',condition,'.csv')
          else paste('All DE predicted TF for ',condition,'.csv')
        }
      },
      content = function(file) {
        if (as.numeric(input$datachoice7==1)){
        #sort by adjusted p value.
        print('heyho')
        result<-predicted_TF()[[1]]
        df<-as.data.frame(result[[row]][[col]])

        df_final<- df[order(df$padj),]
        colnames(df_final)[1]<-"Overall mean"
        for (i in 8:length(colnames(df_final)))
        {
          colnames(df_final)[i]<-paste(colnames(df_final)[i],"mean")
        }
        #write.csv(df_final, file)
        nam<-"Sheet 1"
        combo<-combination()
        condition<-combo()[[row]]
        condition<-str_replace_all(condition,"[^[:alnum:]]",".")
        if(col==1) nam<-paste('Up regulated Kegg for ',condition)
        else if(col==2) nam<-paste('Down regulated Kegg for ',condition)
        else if(col==3) nam<-paste('regulated Kegg for ',condition)
        
        M <- as.matrix(df_final)
        wb <- createWorkbook()
        addWorksheet(wb, sheetName = "predicted TF table")
        writeData(wb = wb, sheet = 1, x = M, colNames = T, rowNames = T)
        saveWorkbook(wb, file)

        }
        else {
          #sort by adjusted p value.

          result<-predicted_TF()[[1]]
          df<-as.data.frame(result[[row]][[col]])

          df_final<- df[order(df$padj),]
          colnames(df_final)[1]<-"Overall mean"
          for (i in 8:length(colnames(df_final)))
          {
            colnames(df_final)[i]<-paste(colnames(df_final)[i],"mean")
          }

          nam<-"Sheet 1"
          combo<-combination()
          condition<-combo()[[row]]
          condition<-str_replace_all(condition,"[^[:alnum:]]",".")
          if(col==1) nam<-paste('Up regulated Kegg for ',condition)
          else if(col==2) nam<-paste('Down regulated Kegg for ',condition)
          else if(col==3) nam<-paste('regulated Kegg for ',condition)
          write.csv(df_final, file)
        }
      }
      
    )
  }
})
})
return(list(overrep_TFs=reactive({predicted_TF()})))
}